### ISSUE TITLE
Problem with Java-driver for Cassandra

### ISSUE THREAD

**Issue by Djimi** [DataStax-Examples/java-cassandra-driver-from3x-to4x#4]
Hi, I saw that page: https://docs.datastax.com/en/developer/java-driver/4.14/manual/mapper/daos/

It is written that we can use inheritance for the DAO classes. 

In the example above the ID is from type UUID. But I tried to use Generic and it didn't work.

I tried that:

```
public interface BasicDao<K, T> {

    @Select
    T findById(K key);

    @Insert
    void save(T domainTypeNew);

    @Delete
    void delete(T domainTypeNew);
}
```

and this interface extends the above one:

```

@Dao
public interface DomainDao extends BasicDao<String, Domain> {

}


```

I got the following error:

```
[BasicDao.findById] Invalid parameter list: Select methods that don't use a custom clause must match the primary key components in the exact order (expected primary key of Domain: [java.lang.String]). Mismatch at index 0: K should be java.lang.String
    T findById(K key);

```

So it seems the ID cannot be generic type. Is that true or I am doing something wrong?

Thanks in advance!

**Comment by clun** [comment]
Hi, The annotation `@Select` will look at the method signature by introspection to make sure returned type is a bean annotated with `@Table` and the arguments match the PK of the table. 

I think it does not support generic indeed as the reflection API in java does not allow to know the generic type used at runtime (type erasure). You would have to use a DAO per table.

**Comment by Djimi** [comment]
I was wondering whether I have something like Generic DAO, but you answered my question.

As an improvement, I would suggest thinking about such functionality in future releases of the library -  for example declaring only an interface (with primary key and entity) and only defining the interface (which will inherit another interface with basic select, delete, etc), something like Spring CRUD repository.

Thanks for your swift reply, @clun! 

PS. Keep in mind that something like this works (at least it is possible to compile the code with it):

```
public interface BasicDao<T> {

    @Select
    T findById(String key);

    @Insert
    void save(T domain);

    @Delete
    void delete(T domain);

}
```

So maybe there could be another reason different from type Erasure in Java.
